import { Navigate, Outlet } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';

const ProtectedRoute = () => {
  // Grab the states generated by React Query
  const { data: user, isLoading, isError } = useAuth();

  // 1. Show a loading screen while waiting for the backend to verify the cookie
  if (isLoading) {
    return (
      <div className="h-screen bg-gray-900 text-white flex items-center justify-center">
        Loading...
      </div>
    );
  }

  // 2. If the backend threw a 401 Unauthorized (isError), or no user returned, kick them to login
  if (isError || !user) {
    return <Navigate to="/login" replace />;
  }

  // 3. Cookie is valid! Let them see the protected pages.
  return <Outlet />;
};

export default ProtectedRoute;